<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Título del producto (h1) en la página de detalle (PDP). Clase estable del theming del PDP de MercadoLibre, confirmada en 2 productos distintos durante la exploración.</description>
   <name>lbl_productTitle</name>
   <tag></tag>
   <elementGuidId>1222fbcb-3cb8-47eb-b4c6-952d358c0a8a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>h1.ui-pdp-title</value>
      <webElementGuid>34b5a66e-f6f2-4b94-8421-1bf6464bcbc3</webElementGuid>
   </webElementProperties>
   <locator>h1.ui-pdp-title</locator>
   <locatorCollection>
      <entry><key>ID</key><value></value></entry>
      <entry><key>NAME</key><value></value></entry>
      <entry><key>XPATH</key><value>//h1[contains(@class,'ui-pdp-title')]</value></entry>
      <entry><key>IMAGE</key><value></value></entry>
      <entry><key>ACCESSIBILITY</key><value></value></entry>
      <entry><key>ATTRIBUTES</key><value>//h1[contains(@class,'ui-pdp-title')]</value></entry>
      <entry><key>ANDROID_VIEWTAG</key><value></value></entry>
      <entry><key>IOS_PREDICATE_STRING</key><value></value></entry>
      <entry><key>ANDROID_UI_AUTOMATOR</key><value></value></entry>
      <entry><key>CLASS_NAME</key><value>ui-pdp-title</value></entry>
      <entry><key>CUSTOM</key><value></value></entry>
      <entry><key>IOS_CLASS_CHAIN</key><value></value></entry>
      <entry><key>CSS</key><value>h1.ui-pdp-title</value></entry>
   </locatorCollection>
   <locatorStrategy>CSS</locatorStrategy>
</WebElementEntity>
