<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Campo de búsqueda del header de MercadoLibre (placeholder "Buscar productos, marcas y más…")</description>
   <name>inp_searchBox</name>
   <tag></tag>
   <elementGuidId>69c6bc3a-ae32-4ed8-94a8-91cb26cb026b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#cb1-edit</value>
      <webElementGuid>730647e1-a371-4b62-bc82-c178dd4dacd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>as_word</value>
      <webElementGuid>2bf00534-c1fc-415a-b45b-6a6bb4f8cf15</webElementGuid>
   </webElementProperties>
   <locator>#cb1-edit</locator>
   <locatorCollection>
      <entry><key>ID</key><value>cb1-edit</value></entry>
      <entry><key>NAME</key><value>as_word</value></entry>
      <entry><key>XPATH</key><value>//input[@name='as_word']</value></entry>
      <entry><key>IMAGE</key><value></value></entry>
      <entry><key>ACCESSIBILITY</key><value></value></entry>
      <entry><key>ATTRIBUTES</key><value>//input[@name='as_word']</value></entry>
      <entry><key>ANDROID_VIEWTAG</key><value></value></entry>
      <entry><key>IOS_PREDICATE_STRING</key><value></value></entry>
      <entry><key>ANDROID_UI_AUTOMATOR</key><value></value></entry>
      <entry><key>CLASS_NAME</key><value>nav-search-input</value></entry>
      <entry><key>CUSTOM</key><value></value></entry>
      <entry><key>IOS_CLASS_CHAIN</key><value></value></entry>
      <entry><key>CSS</key><value>#cb1-edit</value></entry>
   </locatorCollection>
   <locatorStrategy>CSS</locatorStrategy>
</WebElementEntity>
