<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Primer producto orgánico (no patrocinado) de los resultados de búsqueda. Los resultados patrocinados ("Ad") en este layout de MercadoLibre usan enlaces de redirección de tracking (click1.mercadolibre.com.co/mclics/...) en vez de enlaces directos a /p/MCO..., por lo que este selector los excluye de forma natural sin necesidad de parsear el texto "Ad".</description>
   <name>item_firstProduct</name>
   <tag></tag>
   <elementGuidId>76ce2675-fdc3-49a6-b714-ac48b495d5c1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>a[href*="/p/MCO"]</value>
      <webElementGuid>e1340c5e-c74e-4b8e-aac6-f0f43f6d9cb1</webElementGuid>
   </webElementProperties>
   <locator>a[href*="/p/MCO"]</locator>
   <locatorCollection>
      <entry><key>ID</key><value></value></entry>
      <entry><key>NAME</key><value></value></entry>
      <entry><key>XPATH</key><value>(//a[contains(@href,"/p/MCO")])[1]</value></entry>
      <entry><key>IMAGE</key><value></value></entry>
      <entry><key>ACCESSIBILITY</key><value></value></entry>
      <entry><key>ATTRIBUTES</key><value>(//a[contains(@href,"/p/MCO")])[1]</value></entry>
      <entry><key>ANDROID_VIEWTAG</key><value></value></entry>
      <entry><key>IOS_PREDICATE_STRING</key><value></value></entry>
      <entry><key>ANDROID_UI_AUTOMATOR</key><value></value></entry>
      <entry><key>CLASS_NAME</key><value></value></entry>
      <entry><key>CUSTOM</key><value></value></entry>
      <entry><key>IOS_CLASS_CHAIN</key><value></value></entry>
      <entry><key>CSS</key><value>a[href*="/p/MCO"]</value></entry>
   </locatorCollection>
   <locatorStrategy>CSS</locatorStrategy>
</WebElementEntity>
